config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show]
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :tags, except: [:index, :new, :create, :edit, :update, :destroy, :show] do
    get 'posts', to: 'posts#search'
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  before_action :set_already_like

  def create
      @like = Like.create(post_id: params[:post_id], user_id: current_user.id)
      redirect_back(fallback_location: root_path)
  end

  def destroy
    @already_like.destroy
    redirect_back(fallback_location: root_path)
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_already_like
    @already_like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<div class="likes">
  <% if @already_like.present? %>
      <%= link_to post_like_path(@post.id, @already_like.id), method: :delete do %>
        <span class="fas fa-star like"></span>
      <% end %>
  <% else %>
    <%= link_to post_likes_path(@post.id), method: :post do %>
      <span class="fas fa-star"></span>
    <% end %>
  <% end %>
  <span class="likes-count"><%= @post.likes.count %></span>
</div>