config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users, only: [:show]
  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create, :destroy]
  end
  resources :tags, except: [:index, :new, :create, :edit, :update, :destroy, :show] do
    get 'posts', to: 'posts#search'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags

  with_options presence: true do
    validates :image
    validates :title
    validates :overview
    validates :programming_languages
    validates :techs
    validates :portfolio_url
    validates :github_url
  end

  def save_tag(sent_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      self.tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      self.tags << new_post_tag
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_already_like, only: [:show], if: :user_signed_in?

  def index
    @posts = Post.includes(:user).order(created_at: :desc)
    @likes = Like.includes(:post)
    @tag_list = Tag.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    tag_list = params[:post][:tag_name].split(nil)
    if @post.save
      @post.save_tag(tag_list)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @post_tags = @post.tags
  end

  def edit
  end

  def update
    tag_list = params[:post][:tag_name].split(nil)
    if @post.update(post_params)
      @post.save_tag(tag_list)
      redirect_to post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.all.order(created_at: :desc)
  end

  private
  def post_params
    params.require(:post).permit(:image, :title, :overview, :programming_languages, :techs, :portfolio_url, :github_url).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_already_like
    @already_like = Like.find_by(post_id:params[:id], user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |f|%>

  <%= render 'error_messages', model: f.object %>

  <div class="field">
    <%= f.label :image, "画像" %><br />
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :title, "タイトル" %><br />
    <%= f.text_field :title, class: 'input-default' %>
  </div>

  <div class="field">
    <%= f.label :overview, "概要" %><br />
    <%= f.text_area :overview, class: "form-text" %>
  </div>

  <div class="field">
    <%= f.label :programming_languages, "プログラミング言語" %><br />
    <%= f.text_area :programming_languages, class: "form-text" %>
  </div>

  <div class="field">
    <%= f.label :techs, "技術" %><br />
    <%= f.text_area :techs, class: "form-text" %>
  </div>

  <div class="field">
    <%= f.label :portfolio_url, "ポートフォリオのURL" %><br />
    <%= f.text_field :portfolio_url, class: 'input-default' %>
  </div>

  <div class="field">
    <%= f.label :github_url, "GitHubのURL" %><br />
    <%= f.text_field :github_url, class: 'input-default' %>
  </div>

  <div class="field">
    <%= f.label :tag_name, "タグ" %>
    <div class="tag-exp">
      <p>半角スペースを入力することで複数のタグを付けることができます</p>
      <p>例：HTML CSS Ruby RubyonRails</p>
    </div>
    <%= f.text_field :tag_name, class: 'input-default' %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: "form-btn"  %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post shadow">
  <%= link_to image_tag(post.image, class: 'post-img'), post_path(post.id) %>
  
  <div class="post-show-tags">
    <div class="tag-header">
      <span class="fas fa-tags"></span>
      <h3 class="tag-title">タグ</h3>
    </div>
    <div class="tags">
      <% post.tags.each do |list| %>
        <span class="tag">
          <%= link_to list.tag_name, tag_posts_path(list.id) %>
        </span>
      <% end %>
    </div>
  </div>

  <h3 class="post-title">
    <%= link_to post.title, post_path(post.id) %>
  </h3>

  <h3 class="overview-title">&lt;概要&gt;</h3>
  <p class="post-overview">
    <%= post.overview %>
  </p>

  <div class="likes">
    <% if post.likes.present? %>
      <span class="fas fa-star like"></span>
      <span class="likes-count"><%= post.likes.count %></span>
    <% else %>
      <p>＊＊＊いいねはまだありません＊＊＊</p>
    <% end %>
  </div>
</div>

app/views/posts/_tag_list.html.erb
<div class="tag-list shadow">
  <div class="tag-header">
    <span class="fas fa-tags"></span>
    <h3 class="tag-title">タグリスト</h3>
  </div>
  <div class="tags">
    <% @tag_list.each do |list| %>
      <div class="tag">
        <%= link_to list.tag_name, tag_posts_path(list.id) %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/header' %>

<div class="main">
  <div class="container">
    <div class="form-wrapper">
      <h2 class="page-heading">編集</h2>
      <%= render partial: 'form', locals: {post: @post} %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'shared/header' %>

<div class="main">
  <div class="container">
    <div class="left-container">
      <div class="post-wrapper">
        <%= render partial: 'post', collection: @posts %>
      </div>
    </div>
    <div class="right-container">
      <%= render partial: 'tag_list', locals: {tag_list: @tag_list} %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'shared/header' %>

<div class="main">
  <div class="container">
    <div class="form-wrapper">
      <h2 class="page-heading">新規投稿</h2>
      <%= render partial: 'form', locals: {post: @post} %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<%= render 'shared/header' %>

<div class="main">
  <div class="container">
    <div class="left-container">
      <div class="post-wrapper">
        <%= render partial: 'post', collection: @posts %>
      </div>
    </div>
    <div class="right-container">
      <%= render 'tag_list' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'shared/header' %>

<div class="post-show">
  <div class="contents">
    <%= image_tag @post.image, class: 'post-show-img' %>
    
    <div class="post-show-tags">
      <div class="tag-header">
        <span class="fas fa-tags"></span>
        <h3 class="tag-title">タグ</h3>
      </div>
      <% @post.tags.each do |list| %>
        <span class="tag">
          <%= link_to list.tag_name, tag_posts_path(list.id) %>
        </span>
      <% end %>
    </div>
  
    <h2 class="post-title">
      <%= @post.title %>
    </h2>
  
    <div class="overview-wrapper">
      <h3 class="show-title">&lt;概要&gt;</h3>
      <p class="show-text">
        <%= simple_format @post.overview %>
      </p>
    </div>

    <div class="programminlanguages-wrapper">
      <h3 class="show-title">&lt;プログラミング言語&gt;</h3>
      <p class="show-text">
        <%= simple_format @post.programming_languages %>
      </p>
    </div>

    <div class="techs-wrapper">
      <h3 class="show-title">&lt;技術&gt;</h3>
      <p class="show-text">
        <%= simple_format @post.techs %>
      </p>
    </div>

    <div class="url-wrapper">
      <h3 class="show-title">&lt;GitHub&gt;</h3>
      <p class="show-text">
        <%= link_to @post.github_url %>
      </p>
    </div>

    <div class="url-wrapper">
      <h3 class="show-title">&lt;URL&gt;</h3>
      <p class="show-text">
      <%= link_to @post.portfolio_url %>
      </p>
    </div>
    
    <%= render 'likes/like' %>

    <% if user_signed_in? && current_user.id == @post.user_id %>
      <div class="post-manage">
        <div class="btn-wrapper">
          <%= link_to "編集", edit_post_path(@post.id), class: "btn edit-btn"%>
          <%= link_to "削除", post_path(@post.id), method: :delete, class: "btn destroy-btn"%>
        </div>
      </div>
    <% end %>
  </div>
  
  <%= render 'comments/comment' %>
</div>